spring:
  application:
    name:
      currencyrate-service
  datasource:
    driver-class-name:
      org.h2.Driver
    username:
      ${h2username}
    password:
      ${h2pass}
    url: jdbc:h2:mem:${dbname}
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto:
        update
  h2:
    console:
      enabled:
        true